/*
#include <stdio.h>  // header file
#include <stdlib.h>
int main(){
    int i,n,r; //r =random number
    printf("Enter the number of random numbers b/w 1 to 100000\n");
    scanf("%d",&n);
     printf("the random numbers is :\n",r);
    for(i=0;i<n;i++)
    {//constant defined in the C standard library (stdlib.h).
        r=rand()%100000+1;  //Since rand() generates a number between 0 and RAND_MAX, rand() % 100000 will generate a number between 0 and 99999.
        //the modulus of any number by 100000 gives a result in the range 0 to 99999.
       
}
return 0;
} 
*/

#include <stdio.h>
#include <stdlib.h>
#include <time.h>
int main() {
    int i, n, r;
    // Seed the random number generator
    srand(time(0)); //ensures that the sequence of random numbers generated is different each time the program runs.
    //srand(time(0)) is a common technique to introduce variability into the sequence of pseudo-random numbers generated by rand() in C programs
    printf("Enter the number of random numbers between 1 and 100000: ");
    scanf("%d", &n);
    printf("The random numbers are:\n");
    for (i = 0; i < n; i++) {
        r = rand() % 100000 + 1;
        printf("%d\n", r);
    }
    return 0;
}

/*import java.util.Random;
import java.util.Scanner;
public class RandomNumberGenerator {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        System.out.print("Enter the number of random numbers between 1 and 100000: ");
        int n = scanner.nextInt();
        Random random = new Random();
        System.out.println("The random numbers are:");
        for (int i = 0; i < n; i++) {
            int randomNumber = random.nextInt(100000) + 1; 
            System.out.println(randomNumber);
        }
        scanner.close();
    }
}
*/
